name: build

on:
  push:
    branch:
      - master

jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clang-format
        run: |
          git submodule update --init --recursive
          docker run --rm -v ${PWD}:/src wiiuenv/clang-format:13.0.0-2 -r ./src ./include
  build-binary:
    name: Build binary
    runs-on: ubuntu-20.04
    needs: clang-format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build artifacts
        run: |
          docker build . -t builder
          docker run --rm -v ${PWD}:/project builder python3 build.py
